services:
  - type: web
    name: stock-watchlist-bot
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CHAT_ID
        sync: false